-- ============================================================
-- 0001_init — Portfolio V3 Initial Migration
--
-- This is the single authoritative migration for a fresh database.
-- It creates every enum, table, index, and foreign key the
-- application needs to run.
--
-- Rules:
--   • Assumes an EMPTY PostgreSQL database. Run once per environment.
--   • Safe on Neon, Supabase, Railway, and local Docker PostgreSQL.
--   • Do NOT edit this file after it has been applied to any
--     environment. Add a new numbered migration instead.
-- ============================================================

-- ─── Enums ───────────────────────────────────────────────────────────────────

CREATE TYPE "Role" AS ENUM (
  'ADMIN',
  'VIEWER'
);

CREATE TYPE "InquiryStatus" AS ENUM (
  'UNREAD',
  'READ',
  'REPLIED',
  'ARCHIVED'
);

CREATE TYPE "EventType" AS ENUM (
  'PAGE_VIEW',
  'BUTTON_CLICK',
  'LINK_CLICK',
  'RESUME_DOWNLOAD',
  'PROJECT_CLICK',
  'CONTACT_SUBMIT',
  'BLOG_READ',
  'SERVICE_INQUIRY',
  'EXTERNAL_LINK'
);

CREATE TYPE "ContentEventType" AS ENUM (
  'PAGE_VIEW',
  'BLOG_VIEW',
  'BLOG_SCROLL',
  'BLOG_LINK_CLICK',
  'BLOG_RELATED_CLICK',
  'PROJECT_VIEW',
  'PROJECT_GITHUB_CLICK',
  'PROJECT_DEMO_CLICK',
  'PROJECT_IMAGE_VIEW',
  'RESUME_PAGE_VISIT',
  'RESUME_DOWNLOAD',
  'SERVICE_PAGE_VISIT',
  'SERVICE_INQUIRY_OPEN',
  'INQUIRY_SUBMIT',
  'EXTERNAL_LINK',
  'BUTTON_CLICK',
  'SESSION_END'
);

CREATE TYPE "ContentType" AS ENUM (
  'BLOG',
  'PROJECT',
  'SERVICE',
  'RESUME',
  'OTHER'
);

CREATE TYPE "VersionType" AS ENUM (
  'BLOG',
  'PROJECT',
  'SERVICE',
  'PROFILE'
);

-- ─── Tables ───────────────────────────────────────────────────────────────────
-- Order: no table references another before it is defined.

-- User
CREATE TABLE "User" (
  "id"        TEXT         NOT NULL,
  "email"     TEXT         NOT NULL,
  "password"  TEXT         NOT NULL,
  "name"      TEXT         NOT NULL,
  "role"      "Role"       NOT NULL DEFAULT 'VIEWER',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- Profile
CREATE TABLE "Profile" (
  "id"           TEXT         NOT NULL,
  "name"         TEXT         NOT NULL,
  "title"        TEXT         NOT NULL,
  "bio"          TEXT         NOT NULL,
  "bioShort"     TEXT         NOT NULL,
  "avatarUrl"    TEXT,
  "email"        TEXT         NOT NULL,
  "phone"        TEXT,
  "location"     TEXT,
  "githubUrl"    TEXT,
  "linkedinUrl"  TEXT,
  "twitterUrl"   TEXT,
  "websiteUrl"   TEXT,
  "skills"       TEXT[]       NOT NULL DEFAULT ARRAY[]::TEXT[],
  "techStack"    TEXT[]       NOT NULL DEFAULT ARRAY[]::TEXT[],
  "yearsExp"     INTEGER      NOT NULL DEFAULT 0,
  "projectCount" INTEGER      NOT NULL DEFAULT 0,
  "clientCount"  INTEGER      NOT NULL DEFAULT 0,
  "available"    BOOLEAN      NOT NULL DEFAULT true,
  "createdAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"    TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Profile_pkey" PRIMARY KEY ("id")
);

-- Project
CREATE TABLE "Project" (
  "id"          TEXT         NOT NULL,
  "title"       TEXT         NOT NULL,
  "description" TEXT         NOT NULL,
  "longDesc"    TEXT,
  "techStack"   TEXT[]       NOT NULL DEFAULT ARRAY[]::TEXT[],
  "githubUrl"   TEXT,
  "liveUrl"     TEXT,
  "imageUrl"    TEXT,
  "featured"    BOOLEAN      NOT NULL DEFAULT false,
  "order"       INTEGER      NOT NULL DEFAULT 0,
  "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Project_pkey" PRIMARY KEY ("id")
);

-- BlogPost
CREATE TABLE "BlogPost" (
  "id"          TEXT         NOT NULL,
  "title"       TEXT         NOT NULL,
  "slug"        TEXT         NOT NULL,
  "excerpt"     TEXT         NOT NULL,
  "content"     TEXT         NOT NULL,
  "coverImage"  TEXT,
  "tags"        TEXT[]       NOT NULL DEFAULT ARRAY[]::TEXT[],
  "published"   BOOLEAN      NOT NULL DEFAULT false,
  "readingTime" INTEGER      NOT NULL DEFAULT 0,
  "views"       INTEGER      NOT NULL DEFAULT 0,
  "publishedAt" TIMESTAMP(3),
  "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP(3) NOT NULL,
  CONSTRAINT "BlogPost_pkey" PRIMARY KEY ("id")
);

-- Service
CREATE TABLE "Service" (
  "id"          TEXT         NOT NULL,
  "title"       TEXT         NOT NULL,
  "description" TEXT         NOT NULL,
  "features"    TEXT[]       NOT NULL DEFAULT ARRAY[]::TEXT[],
  "price"       TEXT         NOT NULL,
  "priceNote"   TEXT,
  "tier"        TEXT         NOT NULL,
  "popular"     BOOLEAN      NOT NULL DEFAULT false,
  "ctaLabel"    TEXT         NOT NULL DEFAULT 'Get Started',
  "order"       INTEGER      NOT NULL DEFAULT 0,
  "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Service_pkey" PRIMARY KEY ("id")
);

-- Testimonial
CREATE TABLE "Testimonial" (
  "id"          TEXT         NOT NULL,
  "name"        TEXT         NOT NULL,
  "role"        TEXT         NOT NULL,
  "company"     TEXT         NOT NULL,
  "content"     TEXT         NOT NULL,
  "avatarUrl"   TEXT,
  "linkedinUrl" TEXT,
  "rating"      INTEGER      NOT NULL DEFAULT 5,
  "featured"    BOOLEAN      NOT NULL DEFAULT false,
  "order"       INTEGER      NOT NULL DEFAULT 0,
  "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Testimonial_pkey" PRIMARY KEY ("id")
);

-- Resume
CREATE TABLE "Resume" (
  "id"            TEXT         NOT NULL,
  "fileName"      TEXT         NOT NULL,
  "fileUrl"       TEXT         NOT NULL,
  "version"       TEXT         NOT NULL,
  "isActive"      BOOLEAN      NOT NULL DEFAULT true,
  "downloadCount" INTEGER      NOT NULL DEFAULT 0,
  "createdAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"     TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Resume_pkey" PRIMARY KEY ("id")
);

-- Inquiry
CREATE TABLE "Inquiry" (
  "id"          TEXT            NOT NULL,
  "name"        TEXT            NOT NULL,
  "email"       TEXT            NOT NULL,
  "subject"     TEXT            NOT NULL,
  "message"     TEXT            NOT NULL,
  "serviceType" TEXT,
  "status"      "InquiryStatus" NOT NULL DEFAULT 'UNREAD',
  "ipAddress"   TEXT,
  "createdAt"   TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP(3)    NOT NULL,
  CONSTRAINT "Inquiry_pkey" PRIMARY KEY ("id")
);

-- Visitor  (parent: PageView, AnalyticsEvent, VisitorSession, ContentEvent)
CREATE TABLE "Visitor" (
  "id"        TEXT         NOT NULL,
  "sessionId" TEXT         NOT NULL,
  "deviceId"  TEXT,
  "ip"        TEXT,
  "country"   TEXT,
  "city"      TEXT,
  "region"    TEXT,
  "timezone"  TEXT,
  "device"    TEXT,
  "browser"   TEXT,
  "os"        TEXT,
  "isMobile"  BOOLEAN      NOT NULL DEFAULT false,
  "referrer"  TEXT,
  "firstSeen" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lastSeen"  TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Visitor_pkey" PRIMARY KEY ("id")
);

-- PageView
CREATE TABLE "PageView" (
  "id"        TEXT         NOT NULL,
  "visitorId" TEXT         NOT NULL,
  "page"      TEXT         NOT NULL,
  "title"     TEXT,
  "referrer"  TEXT,
  "duration"  INTEGER,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PageView_pkey" PRIMARY KEY ("id")
);

-- AnalyticsEvent
CREATE TABLE "AnalyticsEvent" (
  "id"        TEXT         NOT NULL,
  "visitorId" TEXT         NOT NULL,
  "type"      "EventType"  NOT NULL,
  "page"      TEXT,
  "target"    TEXT,
  "metadata"  JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AnalyticsEvent_pkey" PRIMARY KEY ("id")
);

-- ProjectClick
CREATE TABLE "ProjectClick" (
  "id"        TEXT         NOT NULL,
  "projectId" TEXT         NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ProjectClick_pkey" PRIMARY KEY ("id")
);

-- VisitorSession  (parent: ContentEvent.sessionId)
CREATE TABLE "VisitorSession" (
  "id"              TEXT         NOT NULL,
  "visitorId"       TEXT         NOT NULL,
  "ipAddress"       TEXT,
  "deviceId"        TEXT,
  "browser"         TEXT,
  "operatingSystem" TEXT,
  "locationCountry" TEXT,
  "locationCity"    TEXT,
  "entryPage"       TEXT,
  "exitPage"        TEXT,
  "sessionStart"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "sessionEnd"      TIMESTAMP(3),
  "totalDuration"   INTEGER,
  "totalEvents"     INTEGER      NOT NULL DEFAULT 0,
  "pageCount"       INTEGER      NOT NULL DEFAULT 0,
  "navigationPath"  TEXT[]       NOT NULL DEFAULT ARRAY[]::TEXT[],
  CONSTRAINT "VisitorSession_pkey" PRIMARY KEY ("id")
);

-- ContentEvent
CREATE TABLE "ContentEvent" (
  "id"           TEXT               NOT NULL,
  "visitorId"    TEXT               NOT NULL,
  "sessionId"    TEXT,
  "eventType"    "ContentEventType" NOT NULL,
  "pageUrl"      TEXT,
  "contentType"  "ContentType"      NOT NULL DEFAULT 'OTHER',
  "contentId"    TEXT,
  "contentTitle" TEXT,
  "metadata"     JSONB,
  "createdAt"    TIMESTAMP(3)       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ContentEvent_pkey" PRIMARY KEY ("id")
);

-- FeatureFlag
CREATE TABLE "FeatureFlag" (
  "id"          TEXT         NOT NULL,
  "key"         TEXT         NOT NULL,
  "name"        TEXT         NOT NULL,
  "description" TEXT,
  "enabled"     BOOLEAN      NOT NULL DEFAULT true,
  "category"    TEXT         NOT NULL DEFAULT 'general',
  "metadata"    JSONB,
  "updatedBy"   TEXT,
  "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP(3) NOT NULL,
  CONSTRAINT "FeatureFlag_pkey" PRIMARY KEY ("id")
);

-- ContentVersion
CREATE TABLE "ContentVersion" (
  "id"          TEXT          NOT NULL,
  "contentType" "VersionType" NOT NULL,
  "contentId"   TEXT          NOT NULL,
  "version"     INTEGER       NOT NULL,
  "title"       TEXT          NOT NULL,
  "snapshot"    JSONB         NOT NULL,
  "changedBy"   TEXT,
  "changeNote"  TEXT,
  "createdAt"   TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ContentVersion_pkey" PRIMARY KEY ("id")
);

-- ApiLog
CREATE TABLE "ApiLog" (
  "id"           TEXT         NOT NULL,
  "method"       TEXT         NOT NULL,
  "path"         TEXT         NOT NULL,
  "statusCode"   INTEGER      NOT NULL,
  "durationMs"   INTEGER      NOT NULL,
  "ip"           TEXT,
  "userAgent"    TEXT,
  "userId"       TEXT,
  "errorMessage" TEXT,
  "createdAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ApiLog_pkey" PRIMARY KEY ("id")
);

-- CacheEntry
CREATE TABLE "CacheEntry" (
  "key"       TEXT         NOT NULL,
  "value"     JSONB        NOT NULL,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CacheEntry_pkey" PRIMARY KEY ("key")
);

-- ActiveVisitor
CREATE TABLE "ActiveVisitor" (
  "id"          TEXT         NOT NULL,
  "sessionId"   TEXT         NOT NULL,
  "currentPage" TEXT         NOT NULL,
  "country"     TEXT,
  "device"      TEXT,
  "browser"     TEXT,
  "lastPing"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ActiveVisitor_pkey" PRIMARY KEY ("id")
);

-- ─── Unique Constraints ───────────────────────────────────────────────────────

CREATE UNIQUE INDEX "User_email_key"               ON "User"("email");
CREATE UNIQUE INDEX "BlogPost_slug_key"            ON "BlogPost"("slug");
CREATE UNIQUE INDEX "Visitor_sessionId_key"        ON "Visitor"("sessionId");
CREATE UNIQUE INDEX "FeatureFlag_key_key"          ON "FeatureFlag"("key");
CREATE UNIQUE INDEX "ActiveVisitor_sessionId_key"  ON "ActiveVisitor"("sessionId");

-- ─── Indexes ─────────────────────────────────────────────────────────────────

CREATE INDEX "User_email_idx"                           ON "User"("email");

CREATE INDEX "Project_featured_idx"                     ON "Project"("featured");
CREATE INDEX "Project_order_idx"                        ON "Project"("order");

CREATE INDEX "BlogPost_slug_idx"                        ON "BlogPost"("slug");
CREATE INDEX "BlogPost_published_publishedAt_idx"       ON "BlogPost"("published", "publishedAt");

CREATE INDEX "Inquiry_status_idx"                       ON "Inquiry"("status");
CREATE INDEX "Inquiry_createdAt_idx"                    ON "Inquiry"("createdAt");

CREATE INDEX "Visitor_sessionId_idx"                    ON "Visitor"("sessionId");
CREATE INDEX "Visitor_country_idx"                      ON "Visitor"("country");
CREATE INDEX "Visitor_firstSeen_idx"                    ON "Visitor"("firstSeen");

CREATE INDEX "PageView_visitorId_idx"                   ON "PageView"("visitorId");
CREATE INDEX "PageView_page_idx"                        ON "PageView"("page");
CREATE INDEX "PageView_createdAt_idx"                   ON "PageView"("createdAt");

CREATE INDEX "AnalyticsEvent_visitorId_idx"             ON "AnalyticsEvent"("visitorId");
CREATE INDEX "AnalyticsEvent_type_idx"                  ON "AnalyticsEvent"("type");
CREATE INDEX "AnalyticsEvent_createdAt_idx"             ON "AnalyticsEvent"("createdAt");

CREATE INDEX "ProjectClick_projectId_idx"               ON "ProjectClick"("projectId");
CREATE INDEX "ProjectClick_createdAt_idx"               ON "ProjectClick"("createdAt");

CREATE INDEX "VisitorSession_visitorId_idx"             ON "VisitorSession"("visitorId");
CREATE INDEX "VisitorSession_sessionStart_idx"          ON "VisitorSession"("sessionStart");
CREATE INDEX "VisitorSession_locationCountry_idx"       ON "VisitorSession"("locationCountry");

CREATE INDEX "ContentEvent_visitorId_idx"               ON "ContentEvent"("visitorId");
CREATE INDEX "ContentEvent_sessionId_idx"               ON "ContentEvent"("sessionId");
CREATE INDEX "ContentEvent_eventType_idx"               ON "ContentEvent"("eventType");
CREATE INDEX "ContentEvent_contentType_contentId_idx"   ON "ContentEvent"("contentType", "contentId");
CREATE INDEX "ContentEvent_createdAt_idx"               ON "ContentEvent"("createdAt");

CREATE INDEX "FeatureFlag_key_idx"                      ON "FeatureFlag"("key");
CREATE INDEX "FeatureFlag_category_idx"                 ON "FeatureFlag"("category");

CREATE INDEX "ContentVersion_contentType_contentId_idx" ON "ContentVersion"("contentType", "contentId");
CREATE INDEX "ContentVersion_createdAt_idx"             ON "ContentVersion"("createdAt");

CREATE INDEX "ApiLog_path_idx"                          ON "ApiLog"("path");
CREATE INDEX "ApiLog_statusCode_idx"                    ON "ApiLog"("statusCode");
CREATE INDEX "ApiLog_createdAt_idx"                     ON "ApiLog"("createdAt");
CREATE INDEX "ApiLog_durationMs_idx"                    ON "ApiLog"("durationMs");

CREATE INDEX "CacheEntry_expiresAt_idx"                 ON "CacheEntry"("expiresAt");

CREATE INDEX "ActiveVisitor_lastPing_idx"               ON "ActiveVisitor"("lastPing");

-- ─── Foreign Keys ─────────────────────────────────────────────────────────────

ALTER TABLE "PageView"
  ADD CONSTRAINT "PageView_visitorId_fkey"
  FOREIGN KEY ("visitorId") REFERENCES "Visitor"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "AnalyticsEvent"
  ADD CONSTRAINT "AnalyticsEvent_visitorId_fkey"
  FOREIGN KEY ("visitorId") REFERENCES "Visitor"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProjectClick"
  ADD CONSTRAINT "ProjectClick_projectId_fkey"
  FOREIGN KEY ("projectId") REFERENCES "Project"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "VisitorSession"
  ADD CONSTRAINT "VisitorSession_visitorId_fkey"
  FOREIGN KEY ("visitorId") REFERENCES "Visitor"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ContentEvent"
  ADD CONSTRAINT "ContentEvent_visitorId_fkey"
  FOREIGN KEY ("visitorId") REFERENCES "Visitor"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ContentEvent"
  ADD CONSTRAINT "ContentEvent_sessionId_fkey"
  FOREIGN KEY ("sessionId") REFERENCES "VisitorSession"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- ─── Default Feature Flags ────────────────────────────────────────────────────
-- These rows are part of the init migration so the admin panel works
-- immediately after the first deploy without needing a separate seed step.

INSERT INTO "FeatureFlag" ("id", "key", "name", "description", "enabled", "category", "updatedAt") VALUES
  (gen_random_uuid()::text, 'blog_visible',         'Blog Section',           'Show the blog section publicly',         true,  'content',     NOW()),
  (gen_random_uuid()::text, 'projects_visible',     'Projects Section',       'Show the projects section publicly',     true,  'content',     NOW()),
  (gen_random_uuid()::text, 'testimonials_visible', 'Testimonials Section',   'Show the testimonials section publicly', true,  'content',     NOW()),
  (gen_random_uuid()::text, 'services_visible',     'Services Section',       'Show the services section publicly',     true,  'content',     NOW()),
  (gen_random_uuid()::text, 'resume_download',      'Resume Download',        'Allow visitors to download the resume',  true,  'content',     NOW()),
  (gen_random_uuid()::text, 'analytics_enabled',    'Analytics Tracking',     'Enable visitor analytics collection',    true,  'analytics',   NOW()),
  (gen_random_uuid()::text, 'realtime_analytics',   'Real-Time Analytics',    'Enable real-time presence tracking',     true,  'analytics',   NOW()),
  (gen_random_uuid()::text, 'content_versioning',   'Content Versioning',     'Save version history on content edits',  true,  'developer',   NOW()),
  (gen_random_uuid()::text, 'api_logging',          'API Request Logging',    'Log all API requests for diagnostics',   true,  'developer',   NOW()),
  (gen_random_uuid()::text, 'caching_enabled',      'Response Caching',       'Cache frequently requested content',     true,  'performance', NOW()),
  (gen_random_uuid()::text, 'maintenance_mode',     'Maintenance Mode',       'Show maintenance page to visitors',      false, 'system',      NOW()),
  (gen_random_uuid()::text, 'inquiry_form',         'Inquiry / Contact Form', 'Allow visitors to submit inquiries',     true,  'content',     NOW());
