export const inquiryKeys = {
  all: ['inquiries'] as const,
  list: (params: { page: number; status?: string; stage?: string }) => [...inquiryKeys.all, 'list', params] as const,
};

export const adminQueryKeys = {
  dashboard: () => ['admin', 'dashboard'] as const,
  analyticsPage: (days: number) => ['admin', 'analytics-page', days] as const,
  paymentAnalytics: (days: number) => ['admin', 'payment-analytics', days] as const,
  paymentsList: (params: { page: number; source?: string }) => ['admin', 'payments-list', params] as const,
  notifications: () => ['admin', 'notifications'] as const,
  notificationsList: (params: { page: number; unreadOnly: boolean }) => ['admin', 'notifications', 'list', params] as const,
  projects: () => ['admin', 'projects'] as const,
  services: () => ['admin', 'services'] as const,
  blogPosts: () => ['admin', 'blog-posts'] as const,
  testimonials: () => ['admin', 'testimonials'] as const,
  profile: () => ['admin', 'profile'] as const,
  resumes: () => ['admin', 'resumes'] as const,
  customers: (page: number) => ['admin', 'customers', page] as const,
  customerDetail: (id: string) => ['admin', 'customer-detail', id] as const,
  customerSessions: () => ['admin', 'customer-sessions'] as const,
  customerMessages: () => ['admin', 'customer-messages'] as const,
  emailTemplates: () => ['admin', 'email-templates'] as const,
  pageSectionPages: () => ['admin', 'page-section-pages'] as const,
  pageSections: (page: string) => ['admin', 'page-sections', page] as const,
  featureFlags: () => ['admin', 'feature-flags'] as const,
  analyticsSessions: (page: number) => ['admin', 'analytics-sessions', page] as const,
  sessionTimeline: (id: string) => ['admin', 'session-timeline', id] as const,
  diagnostics: (hours: number) => ['admin', 'diagnostics', hours] as const,
  eventLog: (limit: number) => ['admin', 'event-log', limit] as const,
  smartInsights: (days: number) => ['admin', 'smart-insights', days] as const,
  navFlows: (days: number) => ['admin', 'nav-flows', days] as const,
  activeVisitors: () => ['admin', 'active-visitors'] as const,
  search: (q: string) => ['admin', 'search', q] as const,
};
